### ISSUE TITLE
WebRTc + callKit + pushKit

### ISSUE THREAD

**Issue by saroar** [MixinNetwork/ios-app#202]
I like your app and i see code its look beautiful 
i have one app is called AddaMe(AppStoreApple) where i can call functionality but i wrote some mass code like to ask if anybody can help me refactor my code and make it better i can pay for it thanks 
here is my app now 
https://addaa.me

**Comment by saroar** [comment]
also check this 
http://prntscr.com/n3h5ys

**Comment by crossle** [comment]
Yes, CallKit on the road

**Comment by saroar** [comment]
when call kit will be ready @crossle
