### ISSUE TITLE
pod install error 

### ISSUE THREAD

**Issue by chenchizhao** [MixinNetwork/ios-app#349]
![image](https://user-images.githubusercontent.com/6883210/65386930-1a60b100-dd74-11e9-8821-4ef3b954508b.png)

**Comment by crossle** [comment]
Fix on https://github.com/MixinNetwork/ios-app/commit/ef76ef140b0e01a06ff3df3741586a90f39ee8c5

**Comment by chenchizhao** [comment]
![image](https://user-images.githubusercontent.com/6883210/65388559-b80dad80-dd7f-11e9-986a-31535cdee1f4.png)

**Comment by crossle** [comment]
You should use your self firebase config file

**Comment by chenchizhao** [comment]
GoogleService-Info.plist not exist

**Comment by crossle** [comment]
Yes, GoogleService-Info.plist is Google Firebase config file

**Comment by chenchizhao** [comment]
![image](https://user-images.githubusercontent.com/6883210/65388692-eb047100-dd80-11e9-9945-d41b819e51ca.png)

**Comment by chenchizhao** [comment]
![image](https://user-images.githubusercontent.com/6883210/65388898-cf9a6580-dd82-11e9-993b-cf2a76b1a5f6.png)
![image](https://user-images.githubusercontent.com/6883210/65388913-ed67ca80-dd82-11e9-95b9-81119f446d51.png)

**Comment by chenchizhao** [comment]
tks running is ok
