### ISSUE TITLE
Safari 页面能否跳转到 Mixin 打开？

### ISSUE THREAD

**Issue by raimonfuns** [MixinNetwork/ios-app#377]
场景：用户在 safari 中打开我的 mixin dapp，可以通过点击一个按钮，跳转到 mixin。mixin
自动打开当前网页（其实就是在我的页面显示一个按钮【在 Mixin 中打开】）

为什么：我不想让用户在 mixin 和 safari 之间来回跳转。为了让用户更好的使用 mixin 登录、支付功能，我想把用户直接引导到 mixin 内的 web view，然后再开始使用，这样更流畅。

问题：这个是否已经有实现好了的协议？或者是否可以支持？

**Comment by raimonfuns** [comment]
类似这样
![image](https://user-images.githubusercontent.com/8716838/68729326-9ead1300-0604-11ea-92bd-4c296de5aa44.png)

**Comment by over140** [comment]
https://github.com/MixinNetwork/ios-app/commit/5f2ca16a6ff41b5e6c4a70e4fa69c142429f2eeb

下个版本会支持，可以直接在网页里唤起机器人主页，测试 mixin://apps/71ae9403-9d20-4772-b47a-729e0cc3648b?action=open
