### ISSUE TITLE
remove PuskKit

### ISSUE THREAD

**Issue by saroar** [MixinNetwork/ios-app#410]
https://github.com/MixinNetwork/ios-app/commit/a87a9bd190a3e2a6698b37e2b3d8681e385552ce

are you guys going to remove PuskKit if yes how call will work

**Comment by wuyuehyang** [comment]
> [a87a9bd](https://github.com/MixinNetwork/ios-app/commit/a87a9bd190a3e2a6698b37e2b3d8681e385552ce)
> 
> are you guys going to remove PuskKit if yes how call will work

Voice call notifications will be pushed by APN service
