### ISSUE TITLE
iOS PushKit integration

### ISSUE THREAD

**Issue by wuyuehyang** [MixinNetwork/ios-app#497]
For better experience receiving incoming VoIP calls, we'd like to integrate PushKit notifications.

PushKit notification will be sent if both conditions are true:
1. iOS device running Mixin Messenger with version greater than 0.24.8
2. Receiver got message with category of WEBRTC_AUDIO_OFFER ~~/ WEBRTC_AUDIO_CANCEL~~ while client is offline from WebSocket

Question: should we put SDP description into notification payload?

**Comment by cedricfung** [comment]
When user accepts or declines the call, should the app need to connect the WebSocket and send blaze message?

**Comment by wuyuehyang** [comment]
> When user accepts or declines the call, should the app need to connect the WebSocket and send blaze message?

Yes, it can be performed with VoIP background mode.

**Comment by cedricfung** [comment]
I think I get it, whenever connect the WebSocket, the app need to wait all the pending messages until the OFFER message to get the SDP info, until then the app can't send any messages to answer the call. 

If the SDP info included in the PushKit payload, then the app would be able to send ANSWER or DECLINE message as soon as WebSocket connected, no need to wait all pending messages to get the SDP.

**Comment by wuyuehyang** [comment]
The main point of new VoIP restriction is reporting incoming call to CallKit when PushKit notification is received, **with no delay**. That requires some key information(two ids and a name) to be provided in the payload.
As long as the restriction is satisfied, app won't be complaining about it, the underlying data exchange can be performed by any means. A full BlazeMessageData is only for easier implementation.

**Comment by cedricfung** [comment]
Maybe it won't help a lot for speeding up the WebRTC connection just with the SDP in payload. Because after callee ANSWER with the SDP, it still needs to wait all pending messages to receive further ICE messages to establish the connection. Then it's better to not including those messages in PushKit payload.

Otherwise, if it was possible to speed up the PeerConnection establishment, without waiting pending messages, we could include SDP in Pushkit payload.

@crossle

**Comment by crossle** [comment]
If you didn’t put caller information in your notification’s payload, call the reportCall(with:updated:) method of your app's provider object to update the calling interface. You can call that method at any time to update calls. For example, call it after your app fetches updated caller information from your VoIP server.

**Comment by cedricfung** [comment]
It's OK to include caller's information to present the CallKit UI instantly for better user experience.

The question is whether to include SDP, would it help with faster PeerConnection.

**Comment by wuyuehyang** [comment]
> If you didn’t put caller information in your notification’s payload, call the reportCall(with:updated:) method of your app's provider object to update the calling interface. You can call that method at any time to update calls. For example, call it after your app fetches updated caller information from your VoIP server.

It's OK to update username after, but the call's UUID and caller's user_id is required for unique constraint of a call.

**Comment by jadeydi** [comment]
> It's OK to include caller's information to present the CallKit UI instantly for better user experience.
> 
> The question is whether to include SDP, would it help with faster PeerConnection.



> Maybe it won't help a lot for speeding up the WebRTC connection just with the SDP in payload. Because after callee ANSWER with the SDP, it still needs to wait all pending messages to receive further ICE messages to establish the connection. Then it's better to not including those messages in PushKit payload.
> 
> That said, we should include the full caller view in PushKit payload, and I think the message id is already included?
> 
> Otherwise, if it was possible to speed up the PeerConnection establishment, without waiting pending messages, we could include SDP in Pushkit payload.
> 
> @crossle

**Comment by over140** [comment]
#503
