### ISSUE TITLE
哪个版本 可以再 iOS11版本系统上安装运行呀 最新mixin版本只能在iOS12或以上安装运行吗？？？

### ISSUE THREAD

**Issue by t-o-n-y-w** [MixinNetwork/ios-app#649]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

### Step 2: Describe your environment

  * Device: _____
  * OS version: _____
  * App version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by crossle** [comment]
No version support iOS 11, please upgrade your OS version.
