### ISSUE TITLE
invalidRequestData

### ISSUE THREAD

**Issue by vAIF-LLC** [MixinNetwork/ios-app#685]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.

### Step 2: Describe your environment

  * Device: iPhone 11 Pro Max
  * OS version: ios 14
  * App version: N/A
  
### Step 3: Describe the problem:
When Running the app and trying to signup an error keeps getting presented(Invalid request data).

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by crossle** [comment]
https://github.com/MixinNetwork/ios-app/issues/658
