### ISSUE TITLE
Wallet "Send" flow dead-ends in "Insufficient transaction fee"

### ISSUE THREAD

**Issue by seanahrens** [MixinNetwork/ios-app#696]
### Step 2: Describe your environment

  * Device: iPhone 12 Pro Max
  * OS version: iOS 14.6
  * App version: 0.30.7
  
### Step 3: Describe the problem:

Attempting to withdraw USDC to address errors with "Insufficient transaction fee" regardless of amount specified to withdraw.

#### Steps to reproduce:

  1. Open USD-C wallet
  2. Tap Send
  3. Choose USD-C address
  4. Type amount, eg. 100 USD.
  5. Tap Continue. Type PIN.
  
#### Observed Results:

  * The screen shows "Insufficient transaction fee"
  
#### Expected Results:

  * I expected the transaction to succeed, or see a descriptive error that told me how to change the withdrawal to succeed.

**Comment by cedricfung** [comment]
Because USDC is an Ethereum asset, you need ETH to pay the gas.
