### ISSUE TITLE
can not find Mixin-Keys and GoogleService-Info plist files error when build the proejct

### ISSUE THREAD

**Issue by sandalwoods** [MixinNetwork/ios-app#875]
### Step 2: Describe your environment

  * Device: __MacBook Pro___
  * OS version: _macOS 12.0.1____
  * Xcode version: 13.1
  
### Step 3: Describe the problem:
- I cloned the ios-app to my local machine
- I ran: pod install --no-repo-update
- open the  Minxin.xcworkspace in Xcode(13.1)
-  click 'Run' button, below error happened that make build failed:
error: Build input file cannot be found: '/Users/user1/mixin-network/ios-app/Mixin/Supporting Files/Mixin-Keys.plist' (in target 'MixinNotificationService' from project 'Mixin'
<img width="1167" alt="截屏2021-11-29 下午6 25 02" src="https://user-images.githubusercontent.com/40709372/143851010-4527813f-92e6-4016-946f-6a68b98a5468.png">
)

**Comment by crossle** [comment]
Register your self GoogleService-Info plist from Firebase.

**Comment by sysbol** [comment]
你好，你的Mixin-Keys.plist是怎么配置的，我遇到了跟你一样的问题 提示没有这个文件
