### ISSUE TITLE
Git tag new & old releases

### ISSUE THREAD

**Issue by emanuelb** [MixinNetwork/ios-app#968]
This repo contain tags for old releases, the latest tag & release is: v0.34.2 released on: Jan 31, 2022 
https://github.com/MixinNetwork/ios-app/releases
https://github.com/MixinNetwork/ios-app/tags

while the Apple Store version currently is: 0.35.2 released on: Mar 4, 2022
https://apps.apple.com/app/mixin/id1322324266

Please git tag all releases that are published to Apple Store, and use github releases and add .ipa to them as asset as well

**Comment by wuyuehyang** [comment]
From now on, new versions released to App Store will be tagged as soon as possible.
