### ISSUE TITLE
Project can be build successfully, but cannot be run on the simulator.

### ISSUE THREAD

**Issue by sunimp** [MixinNetwork/ios-app#991]
### Step 1: Are you in the right place?

  * Could builds, but doesn't run.

### Step 2: Describe your environment

  * Device: MacBook Pro 16" 2021 M1 Pro
  * OS version: 12.3.1 (Build 21E258), iPhone Simulator iPhone 13 Pro 15.2
  * App version: Tag v0.35.5
  
#### Steps to reproduce:

  1.  clone project
  2.  pod install 
  3. run Mixin.xcworkspace
  
#### Observed Results:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/16975429/165467781-fb1844a8-a2b9-4154-bf45-5edbf907daa2.png">
  
#### Expected Results:

  * Run Success.
  
#### Relevant Code:

  ```
Details

Executable Not Found
Domain: DVTMachOErrorDomain
Code: 5
Recovery Suggestion: /Users/sun/Library/Developer/Xcode/DerivedData/Mixin-gofjgczcakgushbcwbjqikrirkjh/Build/Products/Debug-iphonesimulator/Mixin.app is not a valid path to an executable file. Please rebuild the project to ensure that all required executables are created. Check your project settings to ensure that a valid executable will be built.
User Info: {
    DVTErrorCreationDateKey = "2022-04-27 07:36:23 +0000";
}
--
System Information
macOS Version 12.3.1 (Build 21E258)
Xcode 13.2.1 (19586) (Build 13C100)
Timestamp: 2022-04-27T15:36:23+08:00

  ````

**Comment by wuyuehyang** [comment]
iOS Simulator on M1 Mac will be supported after WebRTC's branch-heads/4844 is released
See [https://bugs.chromium.org/p/webrtc/issues/detail?id=13488](WebRTC)
