### ISSUE TITLE
cannot be found 'Mixin-keys.plist'

### ISSUE THREAD

**Issue by sysbol** [MixinNetwork/ios-app#992]
### Step 1: Are you in the right place?

  * Could not build
### Step 2: Describe your environment

  * Device: _MacBook Pro (13-inch,2019)____
  * OS version: _____macOS Monterey 版本12.2.1 
  * App version: _____Tab v0.35.5
  
#### Steps to reproduce:

  1. clone project
  2. pod install
  3. build MiXin.xcworkspace
  
#### Observed Results:

  *Build input file cannot be found: '/Users/user/Downloads/ios-app-master/Mixin/Supporting Files/Mixin-Keys.plist' (in target 'MixinNotificationService' from project 'Mixin')

![image](https://user-images.githubusercontent.com/6174835/165662778-c54b3b44-5b9c-4054-8443-75210560b6aa.png)

  
#### Expected Results:

  * If I create a mixin-keys. plist file, do I need to add data to it? 
  * thank you

**Comment by wuyuehyang** [comment]
See [https://github.com/MixinNetwork/ios-app/tree/feature/apikey](apikey)
There's a template file committed to the branch and you need to fill it with your keys.
